CREATE TABLE account (
    id        BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT         NOT NULL REFERENCES client(id) ON DELETE CASCADE,
    type      VARCHAR(255)   NOT NULL,
    balance   NUMERIC(15, 2) DEFAULT 0.00
);