CREATE SEQUENCE IF NOT EXISTS transaction_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS transaction (
    id         BIGINT         PRIMARY KEY,
    account_id BIGINT         NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    amount     NUMERIC(15, 2) NOT NULL,
    create_at  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);